@startuml

package com.acme.sales.model {
    class Pax <<Value Object>> {
        + String fName
        + String mName
        + String lName
        + int age
    }
    note  bottom of Pax
        This the Pax class that has minimal info needed in Sales domain
        The passenger information is persisted as part of the proposal
    end note
}

title  Pax or Passenger Class\n\n
footer \n\n Part of a course on Microservices \n Copyright 2021. For more info visit http://ACloudFan.com \n
@enduml