@startuml

autonumber
Customer -> "Sales Agent" : Identifies + provides desired destination, budget, preferences ...

"Sales Agent" -> "Sales System" : Find customer using email/phone or Add Customer as new customer

"Sales Agent" -> "Sales System" : Selects Vacation Packages

"Sales Agent" -> "Customer" : Describes the various products

"Sales Agent" -> "Sales System" : Creates 1 or more proposals

'Following lines to be uncommented when instructed (later lecture)
'"Sales Agent"-> "Pricing Service" : Price the Proposal
'"Pricing Service"-> "Sales Agent" : Update total Price for proposals (includes taxes & surcharges)

"Sales Agent" -> "Customer" : Describes the proposals

"Customer" -> "Sales Agent" : Selects a Proposal

"Sales Agent" -> "Sales System" : Confirms and initiates booking

title Proposal creation sequence\n\n
footer \n\n\n Part of a course on Microservices \n Copyright @ 2021. For more info visit http://ACloudFan.com \n
@enduml

