@startuml


package com.acme.sales.model {
    class VacationPackage <<Entity>> {
        + String : name

        - ArrayList : reservations

        + ArrayList : generateReservationholders()

    }
    note  top of VacationPackage:"Vacation package has the details for the ACME product"
    note right of VacationPackage::"name"
            A Vacation Package is identified by a short name
    end note
    note right of VacationPackage::"reservations"
            A List of Reservation objects that represents parts of the package
            The instances of Reservation here are the <b>Place Holders</b>
            These objects are used for creating the actual instances in the
            <b>Proposal</b> and <b>BookingConfirmation</b>
    end note
    note right of VacationPackage::"generateReservationholders"
            This function clones the Reservation <i>Pace Holders</i>
    end note
}


package com.acme.sales.model.booking {
    class Reservation {}
}

'Uncomment the below to see the complete Reservation mdodel
'!include reservation.puml

'Cannot exist w/o VacationPackage
VacationPackage "1" *--  "*" Reservation

title Vacation Package Class \n \n
footer \n Part of a course on Microservices \n Copyright 2021. For more info visit http://ACloudFan.com \n
@enduml

